# Generated by Django 3.0.6 on 2025-08-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rolemapping_rolemaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonalprofile',
            name='profilephoto',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
