# Generated by Django 3.0.6 on 2025-08-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_message_read_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read_by',
        ),
    ]
