# Generated by Django 3.0.6 on 2025-08-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_remove_message_read_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
