# Generated by Django 4.2.24 on 2025-09-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_message_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
