# Generated by Django 4.2.24 on 2025-09-17 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notification',
        ),
    ]
