# Generated by Django 4.2.24 on 2025-09-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_id_alter_jobcomment_id_alter_joblike_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='job_images/'),
        ),
    ]
